using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoFeatureFlag;

[Generator]
public sealed class AutoFeatureFlagGenerator : IIncrementalGenerator
{
    // ── Core types always emitted into every consuming project ───────────────
    private const string CoreSource = @"// <auto-generated by Swevo.AutoFeatureFlag/>
#nullable enable
using System.Collections.Concurrent;

namespace AutoFeatureFlag
{
    /// <summary>
    /// Marks an enum as a feature flag set.
    /// The generator will produce a strongly-typed I{EnumName}Flags interface
    /// and a {EnumName}Flags implementation backed by an IFeatureFlagProvider.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    public sealed class FeatureFlagsAttribute : System.Attribute { }

    /// <summary>Runtime contract for reading and toggling feature flags.</summary>
    public interface IFeatureFlagProvider
    {
        bool IsEnabled(string flagName);
        void Enable(string flagName);
        void Disable(string flagName);
        void SetEnabled(string flagName, bool enabled);
    }

    /// <summary>
    /// Thread-safe in-memory implementation of IFeatureFlagProvider.
    /// All flags default to <c>false</c> (disabled) until explicitly enabled.
    /// Ideal for tests and development environments.
    /// </summary>
    public sealed class InMemoryFeatureFlagProvider : IFeatureFlagProvider
    {
        private readonly ConcurrentDictionary<string, bool> _flags = new ConcurrentDictionary<string, bool>();

        public bool IsEnabled(string flagName)
            => _flags.TryGetValue(flagName, out var enabled) && enabled;

        public void Enable(string flagName) => _flags[flagName] = true;

        public void Disable(string flagName) => _flags[flagName] = false;

        public void SetEnabled(string flagName, bool enabled) => _flags[flagName] = enabled;
    }
}
";

    // ── Diagnostics ──────────────────────────────────────────────────────────
    private static readonly DiagnosticDescriptor AFF001 = new DiagnosticDescriptor(
        id: "AFF001",
        title: "[FeatureFlags] enum has no members",
        messageFormat: "'{0}' has [FeatureFlags] but defines no enum members. Add values to generate feature flag properties.",
        category: "AutoFeatureFlag",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    // ── Data model ───────────────────────────────────────────────────────────
    private sealed class FlagModel
    {
        public string TypeName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public ImmutableArray<string> Members { get; set; } = ImmutableArray<string>.Empty;
    }

    // ── Initialize ───────────────────────────────────────────────────────────
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("AutoFeatureFlag.Core.g.cs", CoreSource));

        var flags = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoFeatureFlag.FeatureFlagsAttribute",
                predicate: static (n, _) => n is EnumDeclarationSyntax,
                transform: Transform)
            .Where(x => x is not null)
            .Select((x, _) => x!);

        context.RegisterSourceOutput(flags, Generate);
    }

    // ── Transform ────────────────────────────────────────────────────────────
    private static FlagModel? Transform(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        if (typeSymbol.TypeKind != TypeKind.Enum) return null;

        var ns = typeSymbol.ContainingNamespace is { IsGlobalNamespace: false } ns2
            ? ns2.ToDisplayString()
            : string.Empty;

        var members = typeSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static f => f.IsConst)
            .Select(static f => f.Name)
            .ToImmutableArray();

        return new FlagModel
        {
            TypeName  = typeSymbol.Name,
            Namespace = ns,
            Members   = members
        };
    }

    // ── Code generation ──────────────────────────────────────────────────────
    private static void Generate(SourceProductionContext ctx, FlagModel model)
    {
        if (model.Members.IsEmpty)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(AFF001, Location.None, model.TypeName));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Swevo.AutoFeatureFlag/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(model.Namespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var interfaceName = $"I{model.TypeName}Flags";
        var className     = $"{model.TypeName}Flags";

        // Interface
        sb.AppendLine($"    /// <summary>Strongly-typed feature flag contract generated from <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"    public interface {interfaceName}");
        sb.AppendLine("    {");
        foreach (var member in model.Members)
            sb.AppendLine($"        bool Is{member}Enabled {{ get; }}");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Implementation class
        sb.AppendLine($"    /// <summary>Generated implementation of <see cref=\"{interfaceName}\"/> backed by an <see cref=\"global::AutoFeatureFlag.IFeatureFlagProvider\"/>.</summary>");
        sb.AppendLine($"    public sealed class {className} : {interfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::AutoFeatureFlag.IFeatureFlagProvider _provider;");
        sb.AppendLine();
        sb.AppendLine($"        public {className}(global::AutoFeatureFlag.IFeatureFlagProvider provider) => _provider = provider;");
        sb.AppendLine();
        foreach (var member in model.Members)
            sb.AppendLine($"        public bool Is{member}Enabled => _provider.IsEnabled(\"{member}\");");
        sb.AppendLine("    }");

        if (hasNs) sb.AppendLine("}");

        ctx.AddSource($"AutoFeatureFlag.{model.TypeName}.g.cs", sb.ToString());
    }
}
